language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.3
      env: setup=lowest
    - php: 5.3
      env: setup=stable
      
install:
  - composer self-update
  - if [[ $setup = 'basic' ]]; then composer install --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then composer update --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi
  - phpenv rehash

script:
  - bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
